spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gitfy?characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: mysqlmysql

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.gitfy.gitfyapi.pojo
  # 驼峰命名自动映射
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml
  file:
    name: taffy
    path: /log
  level:
    # root 全局配置
    root: INFO
    # 可以设置指定包的输出级别,这样的话，指定的包，级别以下的日志就不在打印或者写入日志文件
    org.springframework: ERROR
    org.apache: ERROR

